server:
  port: 9527

#eureka:
#  instance:
#    hostname: cloud-gateway-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://www.eureka7000.com:7000/eureka

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 192.168.186.138
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-provider-hystrix-payment  #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
          - Path=/payment/hystrix/ok/*         #断言，路径相匹配的进行路由
          - Before=2020-12-13T11:21:12.052+08:00[Asia/Shanghai]  #只有在这个点之后才能被访问 (before,between)
          - Cookie=username,zzyy
#          - Header=username,\d+
#          - Host=**.xjl.com
#          - Query=password,123qwe     #要有参数名password并且值还要是123qwe才能路由
#          - Method=GET

#        - id: payment_routh2
#          uri: http://localhost:8001
#          uri: lb://cloud-provider-hystrix-payment
#          predicates:
#          - Path=/payment/**