server:
  port: 8002

spring:
  application:
    name: cloud-provider-hystrix-payment
  cloud:
    consul:
      host: 192.168.186.138
      port: 8500
      discovery:
        service-name: ${spring.application.name}