server:
  port: 7000

eureka:
  instance:
    hostname: www.eureka7000.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #集群指向其它eureka
      defaultZone: http://www.eureka7001.com:7001/eureka/
      #单机就是7000自己
#      defaultZone: http://www.eureka7000.com:7000/eureka/
  server:
    #关闭自我保护机制，保证不可用服务呗及时剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000