server:
  port: 80

spring:
  application:
    name: cloud-feign-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7000.com:7000/eureka

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.xjl.service.PaymentFeignService: debug