server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    consul:
      host: 192.168.186.139
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    config:
      server:
        git:
          uri: https://gitlab.com/XJLNB/cloud-config.git #gitlab仓库上面的git仓库名字
          #若仓库是公有的无需账户密码
          username: XJLNB
          password: yz3ZBsic$/=NP`g
          ##搜索目录
          search-paths:
            - cloud-config
      #读取分支
      label: master

      #读取规则
      #   /master/config-dev.yml   /dev/config-dev.yml
      #   /config/dev/master   json串   /config/dev/dev

  rabbitmq:
    host: 192.168.186.139
    port: 5672
    username: guest
    password: guest
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'  #凡是暴露监控、刷新的都要有actuator依赖，bus-refresh就是actuator的刷新操作


        # curl -X POST "http://localhost:3344/actuator/bus-refresh/cloud-config-client:3355"  定点通知
        # curl -X POST "http://localhost:3344/actuator/bus-refresh" 全局广播